# Generated by Django 6.0.5 on 2026-05-21 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('personal', 'Personal Info'), ('interest', 'Interest')], max_length=20)),
                ('title_tr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('value_tr', models.CharField(blank=True, max_length=200)),
                ('value_en', models.CharField(blank=True, max_length=200)),
                ('description_tr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon_class', models.CharField(help_text='Example: bi bi-person', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Card',
                'verbose_name_plural': 'About Cards',
                'ordering': ['card_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_tr', models.CharField(default='Kendim Hakkında', max_length=100)),
                ('eyebrow_en', models.CharField(default='About Me', max_length=100)),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('description_1_tr', models.TextField()),
                ('description_1_en', models.TextField()),
                ('description_2_tr', models.TextField(blank=True)),
                ('description_2_en', models.TextField(blank=True)),
                ('description_3_tr', models.TextField(blank=True)),
                ('description_3_en', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('quote_tr', models.TextField(blank=True)),
                ('quote_en', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Info',
                'verbose_name_plural': 'About Info',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=150)),
                ('year', models.CharField(max_length=20)),
                ('description_tr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(default='İletişim Bilgileri', max_length=150)),
                ('title_en', models.CharField(default='Contact Info', max_length=150)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('location_tr', models.CharField(max_length=150)),
                ('location_en', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Info',
                'verbose_name_plural': 'Contact Info',
            },
        ),
        migrations.CreateModel(
            name='HomeFloatingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('icon_class', models.CharField(help_text='Example: bi bi-code-slash', max_length=100)),
                ('css_class', models.CharField(blank=True, help_text='Example: design, code, creativity', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Floating Card',
                'verbose_name_plural': 'Home Floating Cards',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=200)),
                ('title_en', models.CharField(max_length=200)),
                ('typed_text_tr', models.CharField(max_length=250)),
                ('typed_text_en', models.CharField(max_length=250)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('button_1_text_tr', models.CharField(blank=True, max_length=100)),
                ('button_1_text_en', models.CharField(blank=True, max_length=100)),
                ('button_1_url', models.CharField(blank=True, max_length=200)),
                ('button_2_text_tr', models.CharField(blank=True, max_length=100)),
                ('button_2_text_en', models.CharField(blank=True, max_length=100)),
                ('button_2_url', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home Hero',
                'verbose_name_plural': 'Home Hero',
            },
        ),
        migrations.CreateModel(
            name='ResumeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_tr', models.CharField(max_length=200)),
                ('school_name_en', models.CharField(max_length=200)),
                ('department_tr', models.CharField(blank=True, max_length=200)),
                ('department_en', models.CharField(blank=True, max_length=200)),
                ('date_text_tr', models.CharField(max_length=100)),
                ('date_text_en', models.CharField(max_length=100)),
                ('gpa', models.CharField(blank=True, max_length=50)),
                ('description_tr', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resume Education',
                'verbose_name_plural': 'Resume Education',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResumeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('position_tr', models.CharField(max_length=150)),
                ('position_en', models.CharField(max_length=150)),
                ('date_text_tr', models.CharField(max_length=100)),
                ('date_text_en', models.CharField(max_length=100)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Resume Experience',
                'verbose_name_plural': 'Resume Experience',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Ceren Kodaş CV', max_length=100)),
                ('full_name', models.CharField(default='Ceren Kodaş', max_length=100)),
                ('copyright_text_tr', models.CharField(default='Tüm Hakları Saklıdır', max_length=200)),
                ('copyright_text_en', models.CharField(default='All Rights Reserved', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('icon_class', models.CharField(help_text='Example: bi bi-code-slash', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Skill Group',
                'verbose_name_plural': 'Skill Groups',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='Example: bi bi-linkedin', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Media',
                'verbose_name_plural': 'Social Media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='ExperienceSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_text_tr', models.CharField(max_length=255)),
                ('skill_text_en', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.resumeexperience')),
            ],
            options={
                'verbose_name': 'Experience Skill',
                'verbose_name_plural': 'Experience Skills',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('skill_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.skillgroup')),
            ],
            options={
                'verbose_name': 'Skill Item',
                'verbose_name_plural': 'Skill Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description_tr', models.TextField()),
                ('description_en', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('is_github_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='core.technology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order'],
            },
        ),
    ]
