# Generated by Django 6.0.5 on 2026-05-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tr', models.CharField(max_length=150)),
                ('title_en', models.CharField(max_length=150)),
                ('percentage', models.PositiveIntegerField(default=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Professional Skill',
                'verbose_name_plural': 'Professional Skills',
                'ordering': ['order'],
            },
        ),
    ]
