# Generated by Django 6.0.5 on 2026-05-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_professionalskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
